<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<Icon.Abstract size="40" color={random_hex_color_code()} />
<Icon.Add size="40" color={random_hex_color_code()} />
<Icon.AddR size="40" color={random_hex_color_code()} />
<Icon.Adidas size="40" color={random_hex_color_code()} />
<Icon.Airplane size="40" color={random_hex_color_code()} />
<Icon.Alarm size="40" color={random_hex_color_code()} />
<Icon.Album size="40" color={random_hex_color_code()} />
<Icon.AlignBottom size="40" color={random_hex_color_code()} />
<Icon.AlignCenter size="40" color={random_hex_color_code()} />
<Icon.AlignLeft size="40" color={random_hex_color_code()} />
<Icon.AlignMiddle size="40" color={random_hex_color_code()} />
<Icon.AlignRight size="40" color={random_hex_color_code()} />
<Icon.AlignTop size="40" color={random_hex_color_code()} />
<Icon.Anchor size="40" color={random_hex_color_code()} />
<Icon.AppleWatch size="40" color={random_hex_color_code()} />
<Icon.ArrangeBack size="40" color={random_hex_color_code()} />
<Icon.ArrangeFront size="40" color={random_hex_color_code()} />
<Icon.ArrowAlignH size="40" color={random_hex_color_code()} />
<Icon.ArrowAlignV size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomLeftO size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomLeftR size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomRight size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomRightO size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomRightR size="40" color={random_hex_color_code()} />
<Icon.ArrowDown size="40" color={random_hex_color_code()} />
<Icon.ArrowDownO size="40" color={random_hex_color_code()} />
<Icon.ArrowDownR size="40" color={random_hex_color_code()} />
<Icon.ArrowLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowLeftO size="40" color={random_hex_color_code()} />
<Icon.ArrowLeftR size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDown size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDownC size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDownE size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDownL size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDownR size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeftC size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeftE size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeftL size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeftR size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRight size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRightC size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRightE size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRightL size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRightR size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUp size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUpC size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUpE size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUpL size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUpR size="40" color={random_hex_color_code()} />
<Icon.ArrowRight size="40" color={random_hex_color_code()} />
<Icon.ArrowRightO size="40" color={random_hex_color_code()} />
<Icon.ArrowRightR size="40" color={random_hex_color_code()} />
<Icon.ArrowTopLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowTopLeftO size="40" color={random_hex_color_code()} />
<Icon.ArrowTopLeftR size="40" color={random_hex_color_code()} />
<Icon.ArrowTopRight size="40" color={random_hex_color_code()} />
<Icon.ArrowTopRightO size="40" color={random_hex_color_code()} />
<Icon.ArrowTopRightR size="40" color={random_hex_color_code()} />
<Icon.ArrowUp size="40" color={random_hex_color_code()} />
<Icon.ArrowUpO size="40" color={random_hex_color_code()} />
<Icon.ArrowUpR size="40" color={random_hex_color_code()} />
<Icon.ArrowsBreakeH size="40" color={random_hex_color_code()} />
<Icon.ArrowsBreakeV size="40" color={random_hex_color_code()} />
<Icon.ArrowsExchange size="40" color={random_hex_color_code()} />
<Icon.ArrowsExchangeAlt size="40" color={random_hex_color_code()} />
<Icon.ArrowsExchangeAltV size="40" color={random_hex_color_code()} />
<Icon.ArrowsExchangeV size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandDownLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandDownRight size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandLeftAlt size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandRight size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandRightAlt size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandUpLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpandUpRight size="40" color={random_hex_color_code()} />
<Icon.ArrowsH size="40" color={random_hex_color_code()} />
<Icon.ArrowsHAlt size="40" color={random_hex_color_code()} />
<Icon.ArrowsMergeAltH size="40" color={random_hex_color_code()} />
<Icon.ArrowsMergeAltV size="40" color={random_hex_color_code()} />
<Icon.ArrowsScrollH size="40" color={random_hex_color_code()} />
<Icon.ArrowsScrollV size="40" color={random_hex_color_code()} />
<Icon.ArrowsShrinkH size="40" color={random_hex_color_code()} />
<Icon.ArrowsShrinkV size="40" color={random_hex_color_code()} />
<Icon.ArrowsV size="40" color={random_hex_color_code()} />
<Icon.ArrowsVAlt size="40" color={random_hex_color_code()} />
<Icon.Assign size="40" color={random_hex_color_code()} />
<Icon.Asterisk size="40" color={random_hex_color_code()} />
<Icon.Atlasian size="40" color={random_hex_color_code()} />
<Icon.Attachment size="40" color={random_hex_color_code()} />
<Icon.Attribution size="40" color={random_hex_color_code()} />
<Icon.Awards size="40" color={random_hex_color_code()} />
<Icon.Backspace size="40" color={random_hex_color_code()} />
<Icon.BandAid size="40" color={random_hex_color_code()} />
<Icon.Battery size="40" color={random_hex_color_code()} />
<Icon.BatteryEmpty size="40" color={random_hex_color_code()} />
<Icon.BatteryFull size="40" color={random_hex_color_code()} />
<Icon.Bee size="40" color={random_hex_color_code()} />
<Icon.Bell size="40" color={random_hex_color_code()} />
<Icon.Bitbucket size="40" color={random_hex_color_code()} />
<Icon.Block size="40" color={random_hex_color_code()} />
<Icon.Bmw size="40" color={random_hex_color_code()} />
<Icon.Board size="40" color={random_hex_color_code()} />
<Icon.Bolt size="40" color={random_hex_color_code()} />
<Icon.Bookmark size="40" color={random_hex_color_code()} />
<Icon.BorderAll size="40" color={random_hex_color_code()} />
<Icon.BorderBottom size="40" color={random_hex_color_code()} />
<Icon.BorderLeft size="40" color={random_hex_color_code()} />
<Icon.BorderRight size="40" color={random_hex_color_code()} />
<Icon.BorderStyleDashed size="40" color={random_hex_color_code()} />
<Icon.BorderStyleDotted size="40" color={random_hex_color_code()} />
<Icon.BorderStyleSolid size="40" color={random_hex_color_code()} />
<Icon.BorderTop size="40" color={random_hex_color_code()} />
<Icon.Bot size="40" color={random_hex_color_code()} />
<Icon.Bowl size="40" color={random_hex_color_code()} />
<Icon.Box size="40" color={random_hex_color_code()} />
<Icon.Boy size="40" color={random_hex_color_code()} />
<Icon.Brackets size="40" color={random_hex_color_code()} />
<Icon.Briefcase size="40" color={random_hex_color_code()} />
<Icon.Browse size="40" color={random_hex_color_code()} />
<Icon.Browser size="40" color={random_hex_color_code()} />
<Icon.Brush size="40" color={random_hex_color_code()} />
<Icon.Bulb size="40" color={random_hex_color_code()} />
<Icon.CPlusPlus size="40" color={random_hex_color_code()} />
<Icon.Calculator size="40" color={random_hex_color_code()} />
<Icon.Calendar size="40" color={random_hex_color_code()} />
<Icon.CalendarDates size="40" color={random_hex_color_code()} />
<Icon.CalendarDue size="40" color={random_hex_color_code()} />
<Icon.CalendarNext size="40" color={random_hex_color_code()} />
<Icon.CalendarToday size="40" color={random_hex_color_code()} />
<Icon.CalendarTwo size="40" color={random_hex_color_code()} />
<Icon.Calibrate size="40" color={random_hex_color_code()} />
<Icon.Camera size="40" color={random_hex_color_code()} />
<Icon.Cap size="40" color={random_hex_color_code()} />
<Icon.Captions size="40" color={random_hex_color_code()} />
<Icon.CardClubs size="40" color={random_hex_color_code()} />
<Icon.CardDiamonds size="40" color={random_hex_color_code()} />
<Icon.CardHearts size="40" color={random_hex_color_code()} />
<Icon.CardSpades size="40" color={random_hex_color_code()} />
<Icon.Carousel size="40" color={random_hex_color_code()} />
<Icon.Cast size="40" color={random_hex_color_code()} />
<Icon.Chanel size="40" color={random_hex_color_code()} />
<Icon.Chart size="40" color={random_hex_color_code()} />
<Icon.Check size="40" color={random_hex_color_code()} />
<Icon.CheckO size="40" color={random_hex_color_code()} />
<Icon.CheckR size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleDown size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleDownO size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleDownR size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleLeftO size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleLeftR size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleRight size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleRightO size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleRightR size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleUp size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleUpO size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleUpR size="40" color={random_hex_color_code()} />
<Icon.ChevronDown size="40" color={random_hex_color_code()} />
<Icon.ChevronDownO size="40" color={random_hex_color_code()} />
<Icon.ChevronDownR size="40" color={random_hex_color_code()} />
<Icon.ChevronLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronLeftO size="40" color={random_hex_color_code()} />
<Icon.ChevronLeftR size="40" color={random_hex_color_code()} />
<Icon.ChevronRight size="40" color={random_hex_color_code()} />
<Icon.ChevronRightO size="40" color={random_hex_color_code()} />
<Icon.ChevronRightR size="40" color={random_hex_color_code()} />
<Icon.ChevronUp size="40" color={random_hex_color_code()} />
<Icon.ChevronUpO size="40" color={random_hex_color_code()} />
<Icon.ChevronUpR size="40" color={random_hex_color_code()} />
<Icon.Circleci size="40" color={random_hex_color_code()} />
<Icon.ClapperBoard size="40" color={random_hex_color_code()} />
<Icon.Clipboard size="40" color={random_hex_color_code()} />
<Icon.Close size="40" color={random_hex_color_code()} />
<Icon.CloseO size="40" color={random_hex_color_code()} />
<Icon.CloseR size="40" color={random_hex_color_code()} />
<Icon.Cloud size="40" color={random_hex_color_code()} />
<Icon.Code size="40" color={random_hex_color_code()} />
<Icon.CodeClimate size="40" color={random_hex_color_code()} />
<Icon.CodeSlash size="40" color={random_hex_color_code()} />
<Icon.Coffee size="40" color={random_hex_color_code()} />
<Icon.Collage size="40" color={random_hex_color_code()} />
<Icon.ColorBucket size="40" color={random_hex_color_code()} />
<Icon.ColorPicker size="40" color={random_hex_color_code()} />
<Icon.ComedyCentral size="40" color={random_hex_color_code()} />
<Icon.Comment size="40" color={random_hex_color_code()} />
<Icon.Community size="40" color={random_hex_color_code()} />
<Icon.Components size="40" color={random_hex_color_code()} />
<Icon.Compress size="40" color={random_hex_color_code()} />
<Icon.CompressLeft size="40" color={random_hex_color_code()} />
<Icon.CompressRight size="40" color={random_hex_color_code()} />
<Icon.CompressV size="40" color={random_hex_color_code()} />
<Icon.Controller size="40" color={random_hex_color_code()} />
<Icon.Copy size="40" color={random_hex_color_code()} />
<Icon.Copyright size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleDownLeft size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleDownRight size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleLeftDown size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleLeftUp size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleRightDown size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleRightUp size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleUpLeft size="40" color={random_hex_color_code()} />
<Icon.CornerDoubleUpRight size="40" color={random_hex_color_code()} />
<Icon.CornerDownLeft size="40" color={random_hex_color_code()} />
<Icon.CornerDownRight size="40" color={random_hex_color_code()} />
<Icon.CornerLeftDown size="40" color={random_hex_color_code()} />
<Icon.CornerLeftUp size="40" color={random_hex_color_code()} />
<Icon.CornerRightDown size="40" color={random_hex_color_code()} />
<Icon.CornerRightUp size="40" color={random_hex_color_code()} />
<Icon.CornerUpLeft size="40" color={random_hex_color_code()} />
<Icon.CornerUpRight size="40" color={random_hex_color_code()} />
<Icon.CreditCard size="40" color={random_hex_color_code()} />
<Icon.Crop size="40" color={random_hex_color_code()} />
<Icon.Cross size="40" color={random_hex_color_code()} />
<Icon.Crowdfire size="40" color={random_hex_color_code()} />
<Icon.Crown size="40" color={random_hex_color_code()} />
<Icon.Danger size="40" color={random_hex_color_code()} />
<Icon.DarkMode size="40" color={random_hex_color_code()} />
<Icon.Data size="40" color={random_hex_color_code()} />
<Icon.Database size="40" color={random_hex_color_code()} />
<Icon.Debug size="40" color={random_hex_color_code()} />
<Icon.Designmodo size="40" color={random_hex_color_code()} />
<Icon.Desktop size="40" color={random_hex_color_code()} />
<Icon.DetailsLess size="40" color={random_hex_color_code()} />
<Icon.DetailsMore size="40" color={random_hex_color_code()} />
<Icon.Dialpad size="40" color={random_hex_color_code()} />
<Icon.Dice1 size="40" color={random_hex_color_code()} />
<Icon.Dice2 size="40" color={random_hex_color_code()} />
<Icon.Dice3 size="40" color={random_hex_color_code()} />
<Icon.Dice4 size="40" color={random_hex_color_code()} />
<Icon.Dice5 size="40" color={random_hex_color_code()} />
<Icon.Dice6 size="40" color={random_hex_color_code()} />
<Icon.Digitalocean size="40" color={random_hex_color_code()} />
<Icon.Disc size="40" color={random_hex_color_code()} />
<Icon.DisplayFlex size="40" color={random_hex_color_code()} />
<Icon.DisplayFullwidth size="40" color={random_hex_color_code()} />
<Icon.DisplayGrid size="40" color={random_hex_color_code()} />
<Icon.DisplaySpacing size="40" color={random_hex_color_code()} />
<Icon.DistributeHorizontal size="40" color={random_hex_color_code()} />
<Icon.DistributeVertical size="40" color={random_hex_color_code()} />
<Icon.DockBottom size="40" color={random_hex_color_code()} />
<Icon.DockLeft size="40" color={random_hex_color_code()} />
<Icon.DockRight size="40" color={random_hex_color_code()} />
<Icon.DockWindow size="40" color={random_hex_color_code()} />
<Icon.Dolby size="40" color={random_hex_color_code()} />
<Icon.Dollar size="40" color={random_hex_color_code()} />
<Icon.Dribbble size="40" color={random_hex_color_code()} />
<Icon.Drive size="40" color={random_hex_color_code()} />
<Icon.Drop size="40" color={random_hex_color_code()} />
<Icon.DropInvert size="40" color={random_hex_color_code()} />
<Icon.DropOpacity size="40" color={random_hex_color_code()} />
<Icon.Duplicate size="40" color={random_hex_color_code()} />
<Icon.EditBlackPoint size="40" color={random_hex_color_code()} />
<Icon.EditContrast size="40" color={random_hex_color_code()} />
<Icon.EditExposure size="40" color={random_hex_color_code()} />
<Icon.EditFade size="40" color={random_hex_color_code()} />
<Icon.EditFlipH size="40" color={random_hex_color_code()} />
<Icon.EditFlipV size="40" color={random_hex_color_code()} />
<Icon.EditHighlight size="40" color={random_hex_color_code()} />
<Icon.EditMarkup size="40" color={random_hex_color_code()} />
<Icon.EditMask size="40" color={random_hex_color_code()} />
<Icon.EditNoise size="40" color={random_hex_color_code()} />
<Icon.EditShadows size="40" color={random_hex_color_code()} />
<Icon.EditStraight size="40" color={random_hex_color_code()} />
<Icon.EditUnmask size="40" color={random_hex_color_code()} />
<Icon.Eject size="40" color={random_hex_color_code()} />
<Icon.Enter size="40" color={random_hex_color_code()} />
<Icon.Erase size="40" color={random_hex_color_code()} />
<Icon.Ereader size="40" color={random_hex_color_code()} />
<Icon.Ericsson size="40" color={random_hex_color_code()} />
<Icon.Ethernet size="40" color={random_hex_color_code()} />
<Icon.Euro size="40" color={random_hex_color_code()} />
<Icon.Eventbrite size="40" color={random_hex_color_code()} />
<Icon.Expand size="40" color={random_hex_color_code()} />
<Icon.Export size="40" color={random_hex_color_code()} />
<Icon.Extension size="40" color={random_hex_color_code()} />
<Icon.ExtensionAdd size="40" color={random_hex_color_code()} />
<Icon.ExtensionAlt size="40" color={random_hex_color_code()} />
<Icon.ExtensionRemove size="40" color={random_hex_color_code()} />
<Icon.External size="40" color={random_hex_color_code()} />
<Icon.Eye size="40" color={random_hex_color_code()} />
<Icon.EyeAlt size="40" color={random_hex_color_code()} />
<Icon.Facebook size="40" color={random_hex_color_code()} />
<Icon.Feed size="40" color={random_hex_color_code()} />
<Icon.Figma size="40" color={random_hex_color_code()} />
<Icon.File size="40" color={random_hex_color_code()} />
<Icon.FileAdd size="40" color={random_hex_color_code()} />
<Icon.FileDocument size="40" color={random_hex_color_code()} />
<Icon.FileRemove size="40" color={random_hex_color_code()} />
<Icon.Film size="40" color={random_hex_color_code()} />
<Icon.Filters size="40" color={random_hex_color_code()} />
<Icon.Flag size="40" color={random_hex_color_code()} />
<Icon.FlagAlt size="40" color={random_hex_color_code()} />
<Icon.Folder size="40" color={random_hex_color_code()} />
<Icon.FolderAdd size="40" color={random_hex_color_code()} />
<Icon.FolderRemove size="40" color={random_hex_color_code()} />
<Icon.FontHeight size="40" color={random_hex_color_code()} />
<Icon.FontSpacing size="40" color={random_hex_color_code()} />
<Icon.FormatBold size="40" color={random_hex_color_code()} />
<Icon.FormatCenter size="40" color={random_hex_color_code()} />
<Icon.FormatColor size="40" color={random_hex_color_code()} />
<Icon.FormatHeading size="40" color={random_hex_color_code()} />
<Icon.FormatIndentDecrease size="40" color={random_hex_color_code()} />
<Icon.FormatIndentIncrease size="40" color={random_hex_color_code()} />
<Icon.FormatItalic size="40" color={random_hex_color_code()} />
<Icon.FormatJustify size="40" color={random_hex_color_code()} />
<Icon.FormatLeft size="40" color={random_hex_color_code()} />
<Icon.FormatLineHeight size="40" color={random_hex_color_code()} />
<Icon.FormatRight size="40" color={random_hex_color_code()} />
<Icon.FormatSeparator size="40" color={random_hex_color_code()} />
<Icon.FormatSlash size="40" color={random_hex_color_code()} />
<Icon.FormatStrike size="40" color={random_hex_color_code()} />
<Icon.FormatText size="40" color={random_hex_color_code()} />
<Icon.FormatUnderline size="40" color={random_hex_color_code()} />
<Icon.FormatUppercase size="40" color={random_hex_color_code()} />
<Icon.Framer size="40" color={random_hex_color_code()} />
<Icon.Games size="40" color={random_hex_color_code()} />
<Icon.GenderFemale size="40" color={random_hex_color_code()} />
<Icon.GenderMale size="40" color={random_hex_color_code()} />
<Icon.Ghost size="40" color={random_hex_color_code()} />
<Icon.GhostCharacter size="40" color={random_hex_color_code()} />
<Icon.Gift size="40" color={random_hex_color_code()} />
<Icon.Girl size="40" color={random_hex_color_code()} />
<Icon.GitBranch size="40" color={random_hex_color_code()} />
<Icon.GitCommit size="40" color={random_hex_color_code()} />
<Icon.GitFork size="40" color={random_hex_color_code()} />
<Icon.GitPull size="40" color={random_hex_color_code()} />
<Icon.Gitter size="40" color={random_hex_color_code()} />
<Icon.Glass size="40" color={random_hex_color_code()} />
<Icon.GlassAlt size="40" color={random_hex_color_code()} />
<Icon.Globe size="40" color={random_hex_color_code()} />
<Icon.GlobeAlt size="40" color={random_hex_color_code()} />
<Icon.Google size="40" color={random_hex_color_code()} />
<Icon.GoogleTasks size="40" color={random_hex_color_code()} />
<Icon.Gym size="40" color={random_hex_color_code()} />
<Icon.Hashtag size="40" color={random_hex_color_code()} />
<Icon.Headset size="40" color={random_hex_color_code()} />
<Icon.Heart size="40" color={random_hex_color_code()} />
<Icon.Hello size="40" color={random_hex_color_code()} />
<Icon.Home size="40" color={random_hex_color_code()} />
<Icon.HomeAlt size="40" color={random_hex_color_code()} />
<Icon.HomeScreen size="40" color={random_hex_color_code()} />
<Icon.Icecream size="40" color={random_hex_color_code()} />
<Icon.IfDesign size="40" color={random_hex_color_code()} />
<Icon.Image size="40" color={random_hex_color_code()} />
<Icon.Import size="40" color={random_hex_color_code()} />
<Icon.Inbox size="40" color={random_hex_color_code()} />
<Icon.IndieHackers size="40" color={random_hex_color_code()} />
<Icon.Infinity size="40" color={random_hex_color_code()} />
<Icon.Info size="40" color={random_hex_color_code()} />
<Icon.Inpicture size="40" color={random_hex_color_code()} />
<Icon.InsertAfter size="40" color={random_hex_color_code()} />
<Icon.InsertAfterO size="40" color={random_hex_color_code()} />
<Icon.InsertAfterR size="40" color={random_hex_color_code()} />
<Icon.InsertBefore size="40" color={random_hex_color_code()} />
<Icon.InsertBeforeO size="40" color={random_hex_color_code()} />
<Icon.InsertBeforeR size="40" color={random_hex_color_code()} />
<Icon.Insights size="40" color={random_hex_color_code()} />
<Icon.Instagram size="40" color={random_hex_color_code()} />
<Icon.Internal size="40" color={random_hex_color_code()} />
<Icon.Key size="40" color={random_hex_color_code()} />
<Icon.Keyboard size="40" color={random_hex_color_code()} />
<Icon.Keyhole size="40" color={random_hex_color_code()} />
<Icon.Laptop size="40" color={random_hex_color_code()} />
<Icon.Lastpass size="40" color={random_hex_color_code()} />
<Icon.LayoutGrid size="40" color={random_hex_color_code()} />
<Icon.LayoutGridSmall size="40" color={random_hex_color_code()} />
<Icon.LayoutList size="40" color={random_hex_color_code()} />
<Icon.LayoutPin size="40" color={random_hex_color_code()} />
<Icon.Linear size="40" color={random_hex_color_code()} />
<Icon.Link size="40" color={random_hex_color_code()} />
<Icon.List size="40" color={random_hex_color_code()} />
<Icon.ListTree size="40" color={random_hex_color_code()} />
<Icon.LivePhoto size="40" color={random_hex_color_code()} />
<Icon.Loadbar size="40" color={random_hex_color_code()} />
<Icon.LoadbarAlt size="40" color={random_hex_color_code()} />
<Icon.LoadbarDoc size="40" color={random_hex_color_code()} />
<Icon.LoadbarSound size="40" color={random_hex_color_code()} />
<Icon.Lock size="40" color={random_hex_color_code()} />
<Icon.LockUnlock size="40" color={random_hex_color_code()} />
<Icon.LogIn size="40" color={random_hex_color_code()} />
<Icon.LogOff size="40" color={random_hex_color_code()} />
<Icon.LogOut size="40" color={random_hex_color_code()} />
<Icon.Loupe size="40" color={random_hex_color_code()} />
<Icon.Magnet size="40" color={random_hex_color_code()} />
<Icon.Mail size="40" color={random_hex_color_code()} />
<Icon.MailForward size="40" color={random_hex_color_code()} />
<Icon.MailOpen size="40" color={random_hex_color_code()} />
<Icon.MailReply size="40" color={random_hex_color_code()} />
<Icon.MathDivide size="40" color={random_hex_color_code()} />
<Icon.MathEqual size="40" color={random_hex_color_code()} />
<Icon.MathMinus size="40" color={random_hex_color_code()} />
<Icon.MathPercent size="40" color={random_hex_color_code()} />
<Icon.MathPlus size="40" color={random_hex_color_code()} />
<Icon.Maximize size="40" color={random_hex_color_code()} />
<Icon.MaximizeAlt size="40" color={random_hex_color_code()} />
<Icon.Maze size="40" color={random_hex_color_code()} />
<Icon.MediaLive size="40" color={random_hex_color_code()} />
<Icon.MediaPodcast size="40" color={random_hex_color_code()} />
<Icon.Menu size="40" color={random_hex_color_code()} />
<Icon.MenuBoxed size="40" color={random_hex_color_code()} />
<Icon.MenuCake size="40" color={random_hex_color_code()} />
<Icon.MenuCheese size="40" color={random_hex_color_code()} />
<Icon.MenuGridO size="40" color={random_hex_color_code()} />
<Icon.MenuGridR size="40" color={random_hex_color_code()} />
<Icon.MenuHotdog size="40" color={random_hex_color_code()} />
<Icon.MenuLeft size="40" color={random_hex_color_code()} />
<Icon.MenuLeftAlt size="40" color={random_hex_color_code()} />
<Icon.MenuMotion size="40" color={random_hex_color_code()} />
<Icon.MenuOreos size="40" color={random_hex_color_code()} />
<Icon.MenuRight size="40" color={random_hex_color_code()} />
<Icon.MenuRightAlt size="40" color={random_hex_color_code()} />
<Icon.MenuRound size="40" color={random_hex_color_code()} />
<Icon.MergeHorizontal size="40" color={random_hex_color_code()} />
<Icon.MergeVertical size="40" color={random_hex_color_code()} />
<Icon.Mic size="40" color={random_hex_color_code()} />
<Icon.Microbit size="40" color={random_hex_color_code()} />
<Icon.Microsoft size="40" color={random_hex_color_code()} />
<Icon.MiniPlayer size="40" color={random_hex_color_code()} />
<Icon.Minimize size="40" color={random_hex_color_code()} />
<Icon.MinimizeAlt size="40" color={random_hex_color_code()} />
<Icon.Modem size="40" color={random_hex_color_code()} />
<Icon.Monday size="40" color={random_hex_color_code()} />
<Icon.Moon size="40" color={random_hex_color_code()} />
<Icon.More size="40" color={random_hex_color_code()} />
<Icon.MoreAlt size="40" color={random_hex_color_code()} />
<Icon.MoreO size="40" color={random_hex_color_code()} />
<Icon.MoreR size="40" color={random_hex_color_code()} />
<Icon.MoreVertical size="40" color={random_hex_color_code()} />
<Icon.MoreVerticalAlt size="40" color={random_hex_color_code()} />
<Icon.MoreVerticalO size="40" color={random_hex_color_code()} />
<Icon.MoreVerticalR size="40" color={random_hex_color_code()} />
<Icon.Mouse size="40" color={random_hex_color_code()} />
<Icon.MoveDown size="40" color={random_hex_color_code()} />
<Icon.MoveLeft size="40" color={random_hex_color_code()} />
<Icon.MoveRight size="40" color={random_hex_color_code()} />
<Icon.MoveTask size="40" color={random_hex_color_code()} />
<Icon.MoveUp size="40" color={random_hex_color_code()} />
<Icon.Music size="40" color={random_hex_color_code()} />
<Icon.MusicNote size="40" color={random_hex_color_code()} />
<Icon.MusicSpeaker size="40" color={random_hex_color_code()} />
<Icon.Nametag size="40" color={random_hex_color_code()} />
<Icon.Notes size="40" color={random_hex_color_code()} />
<Icon.Notifications size="40" color={random_hex_color_code()} />
<Icon.Npm size="40" color={random_hex_color_code()} />
<Icon.Oculus size="40" color={random_hex_color_code()} />
<Icon.OpenCollective size="40" color={random_hex_color_code()} />
<Icon.Options size="40" color={random_hex_color_code()} />
<Icon.Organisation size="40" color={random_hex_color_code()} />
<Icon.Overflow size="40" color={random_hex_color_code()} />
<Icon.Pacman size="40" color={random_hex_color_code()} />
<Icon.Password size="40" color={random_hex_color_code()} />
<Icon.PathBack size="40" color={random_hex_color_code()} />
<Icon.PathCrop size="40" color={random_hex_color_code()} />
<Icon.PathDivide size="40" color={random_hex_color_code()} />
<Icon.PathExclude size="40" color={random_hex_color_code()} />
<Icon.PathFront size="40" color={random_hex_color_code()} />
<Icon.PathIntersect size="40" color={random_hex_color_code()} />
<Icon.PathOutline size="40" color={random_hex_color_code()} />
<Icon.PathTrim size="40" color={random_hex_color_code()} />
<Icon.PathUnite size="40" color={random_hex_color_code()} />
<Icon.Patreon size="40" color={random_hex_color_code()} />
<Icon.Paypal size="40" color={random_hex_color_code()} />
<Icon.Pen size="40" color={random_hex_color_code()} />
<Icon.PentagonBottomLeft size="40" color={random_hex_color_code()} />
<Icon.PentagonBottomRight size="40" color={random_hex_color_code()} />
<Icon.PentagonDown size="40" color={random_hex_color_code()} />
<Icon.PentagonLeft size="40" color={random_hex_color_code()} />
<Icon.PentagonRight size="40" color={random_hex_color_code()} />
<Icon.PentagonTopLeft size="40" color={random_hex_color_code()} />
<Icon.PentagonTopRight size="40" color={random_hex_color_code()} />
<Icon.PentagonUp size="40" color={random_hex_color_code()} />
<Icon.Performance size="40" color={random_hex_color_code()} />
<Icon.Pexels size="40" color={random_hex_color_code()} />
<Icon.Phone size="40" color={random_hex_color_code()} />
<Icon.Photoscan size="40" color={random_hex_color_code()} />
<Icon.Piano size="40" color={random_hex_color_code()} />
<Icon.Pill size="40" color={random_hex_color_code()} />
<Icon.Pin size="40" color={random_hex_color_code()} />
<Icon.PinAlt size="40" color={random_hex_color_code()} />
<Icon.PinBottom size="40" color={random_hex_color_code()} />
<Icon.PinTop size="40" color={random_hex_color_code()} />
<Icon.PlayBackwards size="40" color={random_hex_color_code()} />
<Icon.PlayButton size="40" color={random_hex_color_code()} />
<Icon.PlayButtonO size="40" color={random_hex_color_code()} />
<Icon.PlayButtonR size="40" color={random_hex_color_code()} />
<Icon.PlayForwards size="40" color={random_hex_color_code()} />
<Icon.PlayList size="40" color={random_hex_color_code()} />
<Icon.PlayListAdd size="40" color={random_hex_color_code()} />
<Icon.PlayListCheck size="40" color={random_hex_color_code()} />
<Icon.PlayListRemove size="40" color={random_hex_color_code()} />
<Icon.PlayListSearch size="40" color={random_hex_color_code()} />
<Icon.PlayPause size="40" color={random_hex_color_code()} />
<Icon.PlayPauseO size="40" color={random_hex_color_code()} />
<Icon.PlayPauseR size="40" color={random_hex_color_code()} />
<Icon.PlayStop size="40" color={random_hex_color_code()} />
<Icon.PlayStopO size="40" color={random_hex_color_code()} />
<Icon.PlayStopR size="40" color={random_hex_color_code()} />
<Icon.PlayTrackNext size="40" color={random_hex_color_code()} />
<Icon.PlayTrackNextO size="40" color={random_hex_color_code()} />
<Icon.PlayTrackNextR size="40" color={random_hex_color_code()} />
<Icon.PlayTrackPrev size="40" color={random_hex_color_code()} />
<Icon.PlayTrackPrevO size="40" color={random_hex_color_code()} />
<Icon.PlayTrackPrevR size="40" color={random_hex_color_code()} />
<Icon.Plug size="40" color={random_hex_color_code()} />
<Icon.Pocket size="40" color={random_hex_color_code()} />
<Icon.Pokemon size="40" color={random_hex_color_code()} />
<Icon.Polaroid size="40" color={random_hex_color_code()} />
<Icon.Poll size="40" color={random_hex_color_code()} />
<Icon.Presentation size="40" color={random_hex_color_code()} />
<Icon.Printer size="40" color={random_hex_color_code()} />
<Icon.ProductHunt size="40" color={random_hex_color_code()} />
<Icon.Profile size="40" color={random_hex_color_code()} />
<Icon.PullClear size="40" color={random_hex_color_code()} />
<Icon.PushChevronDown size="40" color={random_hex_color_code()} />
<Icon.PushChevronDownO size="40" color={random_hex_color_code()} />
<Icon.PushChevronDownR size="40" color={random_hex_color_code()} />
<Icon.PushChevronLeft size="40" color={random_hex_color_code()} />
<Icon.PushChevronLeftO size="40" color={random_hex_color_code()} />
<Icon.PushChevronLeftR size="40" color={random_hex_color_code()} />
<Icon.PushChevronRight size="40" color={random_hex_color_code()} />
<Icon.PushChevronRightO size="40" color={random_hex_color_code()} />
<Icon.PushChevronRightR size="40" color={random_hex_color_code()} />
<Icon.PushChevronUp size="40" color={random_hex_color_code()} />
<Icon.PushChevronUpO size="40" color={random_hex_color_code()} />
<Icon.PushChevronUpR size="40" color={random_hex_color_code()} />
<Icon.PushDown size="40" color={random_hex_color_code()} />
<Icon.PushLeft size="40" color={random_hex_color_code()} />
<Icon.PushRight size="40" color={random_hex_color_code()} />
<Icon.PushUp size="40" color={random_hex_color_code()} />
<Icon.Qr size="40" color={random_hex_color_code()} />
<Icon.Quote size="40" color={random_hex_color_code()} />
<Icon.QuoteO size="40" color={random_hex_color_code()} />
<Icon.RadioCheck size="40" color={random_hex_color_code()} />
<Icon.RadioChecked size="40" color={random_hex_color_code()} />
<Icon.Ratio size="40" color={random_hex_color_code()} />
<Icon.Read size="40" color={random_hex_color_code()} />
<Icon.Readme size="40" color={random_hex_color_code()} />
<Icon.Record size="40" color={random_hex_color_code()} />
<Icon.Redo size="40" color={random_hex_color_code()} />
<Icon.Remote size="40" color={random_hex_color_code()} />
<Icon.Remove size="40" color={random_hex_color_code()} />
<Icon.RemoveR size="40" color={random_hex_color_code()} />
<Icon.Rename size="40" color={random_hex_color_code()} />
<Icon.Reorder size="40" color={random_hex_color_code()} />
<Icon.Repeat size="40" color={random_hex_color_code()} />
<Icon.Ring size="40" color={random_hex_color_code()} />
<Icon.RowFirst size="40" color={random_hex_color_code()} />
<Icon.RowLast size="40" color={random_hex_color_code()} />
<Icon.Ruler size="40" color={random_hex_color_code()} />
<Icon.SandClock size="40" color={random_hex_color_code()} />
<Icon.Scan size="40" color={random_hex_color_code()} />
<Icon.Screen size="40" color={random_hex_color_code()} />
<Icon.ScreenMirror size="40" color={random_hex_color_code()} />
<Icon.ScreenShot size="40" color={random_hex_color_code()} />
<Icon.ScreenWide size="40" color={random_hex_color_code()} />
<Icon.ScrollH size="40" color={random_hex_color_code()} />
<Icon.ScrollV size="40" color={random_hex_color_code()} />
<Icon.Search size="40" color={random_hex_color_code()} />
<Icon.SearchFound size="40" color={random_hex_color_code()} />
<Icon.SearchLoading size="40" color={random_hex_color_code()} />
<Icon.Select size="40" color={random_hex_color_code()} />
<Icon.SelectO size="40" color={random_hex_color_code()} />
<Icon.SelectR size="40" color={random_hex_color_code()} />
<Icon.Server size="40" color={random_hex_color_code()} />
<Icon.Serverless size="40" color={random_hex_color_code()} />
<Icon.ShapeCircle size="40" color={random_hex_color_code()} />
<Icon.ShapeHalfCircle size="40" color={random_hex_color_code()} />
<Icon.ShapeHexagon size="40" color={random_hex_color_code()} />
<Icon.ShapeRhombus size="40" color={random_hex_color_code()} />
<Icon.ShapeSquare size="40" color={random_hex_color_code()} />
<Icon.ShapeTriangle size="40" color={random_hex_color_code()} />
<Icon.ShapeZigzag size="40" color={random_hex_color_code()} />
<Icon.Share size="40" color={random_hex_color_code()} />
<Icon.Shield size="40" color={random_hex_color_code()} />
<Icon.ShoppingBag size="40" color={random_hex_color_code()} />
<Icon.ShoppingCart size="40" color={random_hex_color_code()} />
<Icon.Shortcut size="40" color={random_hex_color_code()} />
<Icon.Shutterstock size="40" color={random_hex_color_code()} />
<Icon.Sidebar size="40" color={random_hex_color_code()} />
<Icon.SidebarOpen size="40" color={random_hex_color_code()} />
<Icon.SidebarRight size="40" color={random_hex_color_code()} />
<Icon.Signal size="40" color={random_hex_color_code()} />
<Icon.Size size="40" color={random_hex_color_code()} />
<Icon.Sketch size="40" color={random_hex_color_code()} />
<Icon.Slack size="40" color={random_hex_color_code()} />
<Icon.Sleep size="40" color={random_hex_color_code()} />
<Icon.SmartHomeBoiler size="40" color={random_hex_color_code()} />
<Icon.SmartHomeCooker size="40" color={random_hex_color_code()} />
<Icon.SmartHomeHeat size="40" color={random_hex_color_code()} />
<Icon.SmartHomeLight size="40" color={random_hex_color_code()} />
<Icon.SmartHomeRefrigerator size="40" color={random_hex_color_code()} />
<Icon.SmartHomeWashMachine size="40" color={random_hex_color_code()} />
<Icon.Smartphone size="40" color={random_hex_color_code()} />
<Icon.SmartphoneChip size="40" color={random_hex_color_code()} />
<Icon.SmartphoneRam size="40" color={random_hex_color_code()} />
<Icon.SmartphoneShake size="40" color={random_hex_color_code()} />
<Icon.Smile size="40" color={random_hex_color_code()} />
<Icon.SmileMouthOpen size="40" color={random_hex_color_code()} />
<Icon.SmileNeutral size="40" color={random_hex_color_code()} />
<Icon.SmileNoMouth size="40" color={random_hex_color_code()} />
<Icon.SmileNone size="40" color={random_hex_color_code()} />
<Icon.SmileSad size="40" color={random_hex_color_code()} />
<Icon.SmileUpside size="40" color={random_hex_color_code()} />
<Icon.SoftwareDownload size="40" color={random_hex_color_code()} />
<Icon.SoftwareUpload size="40" color={random_hex_color_code()} />
<Icon.SortAz size="40" color={random_hex_color_code()} />
<Icon.SortZa size="40" color={random_hex_color_code()} />
<Icon.SpaceBetween size="40" color={random_hex_color_code()} />
<Icon.SpaceBetweenV size="40" color={random_hex_color_code()} />
<Icon.Spectrum size="40" color={random_hex_color_code()} />
<Icon.Spinner size="40" color={random_hex_color_code()} />
<Icon.SpinnerAlt size="40" color={random_hex_color_code()} />
<Icon.SpinnerTwo size="40" color={random_hex_color_code()} />
<Icon.SpinnerTwoAlt size="40" color={random_hex_color_code()} />
<Icon.Square size="40" color={random_hex_color_code()} />
<Icon.Stack size="40" color={random_hex_color_code()} />
<Icon.Stark size="40" color={random_hex_color_code()} />
<Icon.Stopwatch size="40" color={random_hex_color_code()} />
<Icon.Stories size="40" color={random_hex_color_code()} />
<Icon.Studio size="40" color={random_hex_color_code()} />
<Icon.Style size="40" color={random_hex_color_code()} />
<Icon.Sun size="40" color={random_hex_color_code()} />
<Icon.Support size="40" color={random_hex_color_code()} />
<Icon.Swap size="40" color={random_hex_color_code()} />
<Icon.SwapVertical size="40" color={random_hex_color_code()} />
<Icon.Sweden size="40" color={random_hex_color_code()} />
<Icon.Swiss size="40" color={random_hex_color_code()} />
<Icon.Sync size="40" color={random_hex_color_code()} />
<Icon.Tab size="40" color={random_hex_color_code()} />
<Icon.Tag size="40" color={random_hex_color_code()} />
<Icon.Tally size="40" color={random_hex_color_code()} />
<Icon.TapDouble size="40" color={random_hex_color_code()} />
<Icon.TapSingle size="40" color={random_hex_color_code()} />
<Icon.Template size="40" color={random_hex_color_code()} />
<Icon.Tennis size="40" color={random_hex_color_code()} />
<Icon.Terminal size="40" color={random_hex_color_code()} />
<Icon.Terrain size="40" color={random_hex_color_code()} />
<Icon.Thermometer size="40" color={random_hex_color_code()} />
<Icon.Thermostat size="40" color={random_hex_color_code()} />
<Icon.Tikcode size="40" color={random_hex_color_code()} />
<Icon.Time size="40" color={random_hex_color_code()} />
<Icon.Timelapse size="40" color={random_hex_color_code()} />
<Icon.Timer size="40" color={random_hex_color_code()} />
<Icon.Today size="40" color={random_hex_color_code()} />
<Icon.ToggleOff size="40" color={random_hex_color_code()} />
<Icon.ToggleOn size="40" color={random_hex_color_code()} />
<Icon.ToggleSquare size="40" color={random_hex_color_code()} />
<Icon.ToggleSquareOff size="40" color={random_hex_color_code()} />
<Icon.ToolbarBottom size="40" color={random_hex_color_code()} />
<Icon.ToolbarLeft size="40" color={random_hex_color_code()} />
<Icon.ToolbarRight size="40" color={random_hex_color_code()} />
<Icon.ToolbarTop size="40" color={random_hex_color_code()} />
<Icon.Toolbox size="40" color={random_hex_color_code()} />
<Icon.Touchpad size="40" color={random_hex_color_code()} />
<Icon.Track size="40" color={random_hex_color_code()} />
<Icon.Transcript size="40" color={random_hex_color_code()} />
<Icon.Trash size="40" color={random_hex_color_code()} />
<Icon.TrashEmpty size="40" color={random_hex_color_code()} />
<Icon.Tree size="40" color={random_hex_color_code()} />
<Icon.Trees size="40" color={random_hex_color_code()} />
<Icon.Trello size="40" color={random_hex_color_code()} />
<Icon.Trending size="40" color={random_hex_color_code()} />
<Icon.TrendingDown size="40" color={random_hex_color_code()} />
<Icon.Trophy size="40" color={random_hex_color_code()} />
<Icon.Tv size="40" color={random_hex_color_code()} />
<Icon.Twilio size="40" color={random_hex_color_code()} />
<Icon.Twitter size="40" color={random_hex_color_code()} />
<Icon.UiKit size="40" color={random_hex_color_code()} />
<Icon.Umbrella size="40" color={random_hex_color_code()} />
<Icon.Unavailable size="40" color={random_hex_color_code()} />
<Icon.Unblock size="40" color={random_hex_color_code()} />
<Icon.Undo size="40" color={random_hex_color_code()} />
<Icon.Unfold size="40" color={random_hex_color_code()} />
<Icon.Unsplash size="40" color={random_hex_color_code()} />
<Icon.Usb size="40" color={random_hex_color_code()} />
<Icon.UsbC size="40" color={random_hex_color_code()} />
<Icon.User size="40" color={random_hex_color_code()} />
<Icon.UserAdd size="40" color={random_hex_color_code()} />
<Icon.UserList size="40" color={random_hex_color_code()} />
<Icon.UserRemove size="40" color={random_hex_color_code()} />
<Icon.Userlane size="40" color={random_hex_color_code()} />
<Icon.Vercel size="40" color={random_hex_color_code()} />
<Icon.ViewCols size="40" color={random_hex_color_code()} />
<Icon.ViewComfortable size="40" color={random_hex_color_code()} />
<Icon.ViewDay size="40" color={random_hex_color_code()} />
<Icon.ViewGrid size="40" color={random_hex_color_code()} />
<Icon.ViewList size="40" color={random_hex_color_code()} />
<Icon.ViewMonth size="40" color={random_hex_color_code()} />
<Icon.ViewSplit size="40" color={random_hex_color_code()} />
<Icon.Vinyl size="40" color={random_hex_color_code()} />
<Icon.Voicemail size="40" color={random_hex_color_code()} />
<Icon.VoicemailO size="40" color={random_hex_color_code()} />
<Icon.VoicemailR size="40" color={random_hex_color_code()} />
<Icon.Volume size="40" color={random_hex_color_code()} />
<Icon.Webcam size="40" color={random_hex_color_code()} />
<Icon.Website size="40" color={random_hex_color_code()} />
<Icon.Windows size="40" color={random_hex_color_code()} />
<Icon.WorkAlt size="40" color={random_hex_color_code()} />
<Icon.Yinyang size="40" color={random_hex_color_code()} />
<Icon.Youtube size="40" color={random_hex_color_code()} />
<Icon.ZoomIn size="40" color={random_hex_color_code()} />
<Icon.ZoomOut size="40" color={random_hex_color_code()} />

